name: Test Custom Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run My Custom Action
        id: hello
        uses: ./.github/actions/hello-action
        with:
          name: Singathurai

      - name: Show Output
        run: echo "Custom Action Output = ${{ steps.hello.outputs.message }}"
