  deploy:
    needs:
      - build
      - reusable-build
    runs-on: ubuntu-latest
    environment: production

    concurrency:
      group: production-deployment
      cancel-in-progress: false

    timeout-minutes: 10

    env:
      APP_NAME: "EC2 Deployment"

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::399863053490:role/GitHubActionsOIDCRole
          aws-region: ap-south-1

      - name: Check AWS Identity
        run: aws sts get-caller-identity

      - name: Test continue-on-error
        id: error-test
        continue-on-error: true
        run: |
          echo "This step will fail"
          exit 1

      - name: Check step outcome
        run: echo "Outcome = ${{ steps.error-test.outcome }}"

      - name: Check step conclusion
        run: echo "Conclusion = ${{ steps.error-test.conclusion }}"

      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: build-result-*
          path: downloaded-artifacts
          merge-multiple: true

      - name: Show downloaded artifacts
        run: ls -R downloaded-artifacts

      - name: Run Node Test Composite Action
        uses: ./.github/actions/node-test
        with:
          node-version: "20"

      - name: Deploy to EC2
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "index.html"
          target: "/tmp/"

      - name: Restart Nginx
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo cp /tmp/index.html /var/www/html/index.html
            sudo systemctl restart nginx
