name: Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Show Repository IDs
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Owner ID: ${{ github.repository_owner_id }}"
          echo "Repository ID: ${{ github.repository_id }}"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::399863053490:role/GitHubActionsOIDCRole
          aws-region: ap-south-1

      - name: Check AWS Identity
        run: aws sts get-caller-identity


      - name: Deploy Docker container to EC2
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop github-actions-demo || true
            docker rm github-actions-demo || true
            docker run -d \
              --name github-actions-demo \
              -p 8080:80 \
              ghcr.io/${{ github.repository }}:latest
            docker ps
